// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/today": {
            "get": {
                "description": "Возвращает погоду на текущий день",
                "tags": [
                    "Weather"
                ],
                "summary": "Прогноз погоды на сегодня",
                "parameters": [
                    {
                        "type": "string",
                        "default": "almaty",
                        "description": "Город",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "celsius",
                            "fahrenheit"
                        ],
                        "type": "string",
                        "default": "celsius",
                        "description": "Единицы измерения",
                        "name": "unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TodayWeather"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/weekly": {
            "get": {
                "description": "Возвращает прогноз погоды на 7 дней",
                "tags": [
                    "Weather"
                ],
                "summary": "Получить прогноз на неделю",
                "parameters": [
                    {
                        "type": "string",
                        "default": "almaty",
                        "description": "Название города",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "celsius",
                            "fahrenheit"
                        ],
                        "type": "string",
                        "default": "celsius",
                        "description": "Единицы измерения",
                        "name": "unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.WeeklyWeather"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.DayWeather": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "model.TodayWeather": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "model.WeeklyWeather": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DayWeather"
                    }
                },
                "unit": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Weather API",
	Description:      "API для получения прогноза погоды",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
